# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSzD72lY_SRjLEgyFilHOx3GyNj6NU3v
"""

import pandas as pd
df=pd.read_csv('data.csv')

df['sales_per_product']=df['quantity']*df['price']
df

df.groupby('product')['sales_per_product'].sum()

